### ISSUE TITLE
app crashes when using accessibility service

### ISSUE THREAD

**Issue by DJaeger** [grote/Liberario#75]
The app crashes on click on the search button.
Also the button to change if start- or reachtime does nothing.
This occures if an accessible service is active that uses the following info:

https://developer.android.com/reference/android/accessibilityservice/AccessibilityServiceInfo.html#attr_android:canRequestEnhancedWebAccessibility

If I deactivate all accessible services it works.
If I activate an accessible service which doesn't requested access to this info it also works.
If I activate an accessible service which requested this info it didn't work.

I use the current release version (0.6) on CyanogenMod 11 (Android 4.4.4).

Log will follow.

**Comment by DJaeger** [comment]
I tested with 8 different accessible services and multiple reinstallations of the app.

**Comment by grote** [comment]
Thanks, a log file showing a backtrace of the crash would be really helpful.

**Comment by DJaeger** [comment]
```
D/BackupManagerService(  746): Received broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:de.grobox.liberario flg=0x4000010 (has extras) }
I/ActivityManager(  746): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=de.grobox.liberario cmp=de.grobox.liberario/.MainActivity} from pid 12837
I/ActivityManager(  746): Start proc de.grobox.liberario for activity de.grobox.liberario/.MainActivity: pid=19666 uid=10515 gids={50515, 3003, 1028, 1015}
I/ActivityManager(  746): START u0 {cmp=de.grobox.liberario/.AboutActivity} from pid 19666
I/ActivityManager(  746): START u0 {cmp=de.grobox.liberario/.PickNetworkProviderActivity (has extras)} from pid 19666
I/ActivityManager(  746): Killing 19666:de.grobox.liberario/u0a515 (adj 9): remove task
I/WindowState(  746): WIN DEATH: Window{433e9bd8 u0 de.grobox.liberario/de.grobox.liberario.MainActivity}
I/Timeline( 1442): Timeline: Activity_launch_request id:de.grobox.liberario time:43674198
I/ActivityManager(  746): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.grobox.liberario/.MainActivity bnds=[492,851][714,1101]} from pid 1442
I/ActivityManager(  746): Start proc de.grobox.liberario for activity de.grobox.liberario/.MainActivity: pid=11647 uid=10515 gids={50515, 3003, 1028, 1015}
D/ActivityThread(11647): handleBindApplication:de.grobox.liberario
I/ActivityManager(  746): Displayed de.grobox.liberario/.MainActivity: +634ms
I/Timeline(  746): Timeline: Activity_windows_visible id: ActivityRecord{42846208 u0 de.grobox.liberario/.MainActivity t48} time:43674960
E/AndroidRuntime(11647): Process: de.grobox.liberario, PID: 11647
E/AndroidRuntime(11647): 	at de.grobox.liberario.DateUtils.parseDate(DateUtils.java:62)
E/AndroidRuntime(11647): 	at de.grobox.liberario.DateUtils.mergeDateTime(DateUtils.java:44)
E/AndroidRuntime(11647): 	at de.grobox.liberario.DirectionsFragment$10.onClick(DirectionsFragment.java:261)
W/ActivityManager(  746):   Force finishing activity de.grobox.liberario/.MainActivity
W/ActivityManager(  746): Activity pause timeout for ActivityRecord{42846208 u0 de.grobox.liberario/.MainActivity t48 f}
I/ActivityManager(  746): Process de.grobox.liberario (pid 11647) has died.
I/WindowState(  746): WIN DEATH: Window{42eabb98 u0 de.grobox.liberario/de.grobox.liberario.MainActivity}
```

**Comment by DJaeger** [comment]
```
I/ActivityManager(  746): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.grobox.liberario/.MainActivity bnds=[492,851][714,1101]} from pid 1442
I/ActivityManager(  746): Start proc de.grobox.liberario for activity de.grobox.liberario/.MainActivity: pid=19857 uid=10515 gids={50515, 3003, 1028, 1015}
E/AndroidRuntime(19857): Process: de.grobox.liberario, PID: 19857
E/AndroidRuntime(19857): 	at de.grobox.liberario.DateUtils.parseDate(DateUtils.java:62)
E/AndroidRuntime(19857): 	at de.grobox.liberario.DateUtils.mergeDateTime(DateUtils.java:44)
E/AndroidRuntime(19857): 	at de.grobox.liberario.DirectionsFragment$10.onClick(DirectionsFragment.java:261)
W/ActivityManager(  746):   Force finishing activity de.grobox.liberario/.MainActivity
W/ActivityManager(  746): Activity pause timeout for ActivityRecord{426fddd8 u0 de.grobox.liberario/.MainActivity t77 f}
I/ActivityManager(  746): Process de.grobox.liberario (pid 19857) has died.
I/WindowState(  746): WIN DEATH: Window{4286c520 u0 de.grobox.liberario/de.grobox.liberario.MainActivity}
I/ActivityManager(  746): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.grobox.liberario/.MainActivity bnds=[492,851][714,1101]} from pid 1442
I/ActivityManager(  746): Start proc de.grobox.liberario for activity de.grobox.liberario/.MainActivity: pid=20022 uid=10515 gids={50515, 3003, 1028, 1015}
E/AndroidRuntime(20022): Process: de.grobox.liberario, PID: 20022
E/AndroidRuntime(20022): 	at de.grobox.liberario.DateUtils.parseDate(DateUtils.java:62)
E/AndroidRuntime(20022): 	at de.grobox.liberario.DateUtils.mergeDateTime(DateUtils.java:44)
E/AndroidRuntime(20022): 	at de.grobox.liberario.DirectionsFragment$10.onClick(DirectionsFragment.java:261)
W/ActivityManager(  746):   Force finishing activity de.grobox.liberario/.MainActivity
W/ActivityManager(  746): Activity pause timeout for ActivityRecord{423ded98 u0 de.grobox.liberario/.MainActivity t78 f}
I/ActivityManager(  746): Process de.grobox.liberario (pid 20022) has died.
I/WindowState(  746): WIN DEATH: Window{435cc268 u0 de.grobox.liberario/de.grobox.liberario.MainActivity}
I/ActivityManager(  746): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10304000 cmp=de.grobox.liberario/.MainActivity} from pid 1227
I/ActivityManager(  746): Start proc de.grobox.liberario for activity de.grobox.liberario/.MainActivity: pid=20259 uid=10515 gids={50515, 3003, 1028, 1015}
I/ActivityManager(  746): Killing 20259:de.grobox.liberario/u0a515 (adj 9): remove task
I/WindowState(  746): WIN DEATH: Window{43c66888 u0 de.grobox.liberario/de.grobox.liberario.MainActivity}
I/ActivityManager(  746): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.grobox.liberario/.MainActivity bnds=[492,851][714,1101]} from pid 1442
I/ActivityManager(  746): Start proc de.grobox.liberario for activity de.grobox.liberario/.MainActivity: pid=20355 uid=10515 gids={50515, 3003, 1028, 1015}
E/AccessibilityNodeInfoCache( 2837): Node from: 1139 not from:1145 android.view.accessibility.AccessibilityNodeInfo@233e7; boundsInParent: Rect(0, 342 - 192, 540); boundsInScreen: Rect(563, 1095 - 755, 1293); packageName: de.grobox.liberario; className: android.widget.Button; text: 30; contentDescription: null; viewIdResName: null; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: true; longClickable: true; enabled: true; password: false; scrollable: false; [ACTION_CLICK, ACTION_ACCESSIBILITY_FOCUS]
E/AccessibilityNodeInfoCache( 2837): Node from: 1139 not from:1145 android.view.accessibility.AccessibilityNodeInfo@23406; boundsInParent: Rect(0, 198 - 192, 342); boundsInScreen: Rect(563, 951 - 755, 1095); packageName: de.grobox.liberario; className: android.widget.EditText; text: 29; contentDescription: null; viewIdResName: android:id/numberpicker_input; checkable: false; checked: false; focusable: true; focused: false; selected: false; clickable: true; longClickable: true; enabled: true; password: false; scrollable: false; [ACTION_FOCUS, ACTION_SELECT, ACTION_CLEAR_SELECTION, ACTION_CLICK, ACTION_LONG_CLICK, ACTION_ACCESSIBILITY_FOCUS, ACTION_NEXT_AT_MOVEMENT_GRANULARITY, ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, ACTION_SET_SELECTION]
E/AccessibilityNodeInfoCache( 2837): Node from: 1139 not from:1145 android.view.accessibility.AccessibilityNodeInfo@23425; boundsInParent: Rect(0, 0 - 192, 198); boundsInScreen: Rect(563, 753 - 755, 951); packageName: de.grobox.liberario; className: android.widget.Button; text: 28; contentDescription: null; viewIdResName: null; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: true; longClickable: true; enabled: true; password: false; scrollable: false; [ACTION_CLICK, ACTION_ACCESSIBILITY_FOCUS]
E/AccessibilityNodeInfoCache( 2837): Node from: 1139 not from:1145 android.view.accessibility.AccessibilityNodeInfo@220e4; boundsInParent: Rect(0, 0 - 1026, 1028); boundsInScreen: Rect(27, 483 - 1053, 1511); packageName: de.grobox.liberario; className: android.widget.FrameLayout; text: null; contentDescription: null; viewIdResName: null; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; enabled: true; password: false; scrollable: false; [ACTION_SELECT, ACTION_CLEAR_SELECTION, ACTION_ACCESSIBILITY_FOCUS]
E/AccessibilityNodeInfoCache( 2837): Node from: 1139 not from:1145 android.view.accessibility.AccessibilityNodeInfo@22866; boundsInParent: Rect(0, 0 - 834, 88); boundsInScreen: Rect(123, 559 - 957, 647); packageName: de.grobox.liberario; className: android.widget.TextView; text: Uhrzeit festlegen; contentDescription: null; viewIdResName: android:id/alertTitle; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; enabled: true; password: false; scrollable: false; [ACTION_SELECT, ACTION_CLEAR_SELECTION, ACTION_ACCESSIBILITY_FOCUS, ACTION_NEXT_AT_MOVEMENT_GRANULARITY, ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, ACTION_SET_SELECTION]
E/AccessibilityNodeInfoCache( 2837): Node from: 1139 not from:1145 android.view.accessibility.AccessibilityNodeInfo@22c27; boundsInParent: Rect(0, 0 - 930, 636); boundsInScreen: Rect(75, 705 - 1005, 1341); packageName: de.grobox.liberario; className: android.widget.TimePicker; text: null; contentDescription: null; viewIdResName: android:id/timePicker; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; enabled: true; password: false; scrollable: false; [ACTION_SELECT, ACTION_CLEAR_SELECTION, ACTION_ACCESSIBILITY_FOCUS]
E/AccessibilityNodeInfoCache( 2837): Node from: 1139 not from:1145 android.view.accessibility.AccessibilityNodeInfo@22fe8; boundsInParent: Rect(0, 0 - 930, 144); boundsInScreen: Rect(75, 1343 - 1005, 1487); packageName: de.grobox.liberario; className: android.widget.Button; text: Fertig; contentDescription: null; viewIdResName: android:id/button1; checkable: false; checked: false; focusable: true; focused: false; selected: false; clickable: true; longClickable: false; enabled: true; password: false; scrollable: false; [ACTION_FOCUS, ACTION_SELECT, ACTION_CLEAR_SELECTION, ACTION_CLICK, ACTION_ACCESSIBILITY_FOCUS, ACTION_NEXT_AT_MOVEMENT_GRANULARITY, ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, ACTION_SET_SELECTION]
E/AccessibilityNodeInfoCache( 2837): Node from: 1139 not from:1145 android.view.accessibility.AccessibilityNodeInfo@233a9; boundsInParent: Rect(0, 0 - 192, 540); boundsInScreen: Rect(563, 753 - 755, 1293); packageName: de.grobox.liberario; className: android.widget.NumberPicker; text: null; contentDescription: null; viewIdResName: null; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; enabled: true; password: false; scrollable: true; [ACTION_ACCESSIBILITY_FOCUS, ACTION_SCROLL_FORWARD, ACTION_SCROLL_BACKWARD]
E/AccessibilityNodeInfoCache( 2837): Node from: 1139 not from:1145 android.view.accessibility.AccessibilityNodeInfo@23b2b; boundsInParent: Rect(524192, 0 - 524384, 73); boundsInScreen: Rect(325, 986 - 517, 1059); packageName: de.grobox.liberario; className: android.widget.EditText; text: 12; contentDescription: null; viewIdResName: android:id/numberpicker_input; checkable: false; checked: false; focusable: true; focused: false; selected: false; clickable: true; longClickable: true; enabled: true; password: false; scrollable: false; [ACTION_FOCUS, ACTION_SELECT, ACTION_CLEAR_SELECTION, ACTION_CLICK, ACTION_LONG_CLICK, ACTION_ACCESSIBILITY_FOCUS, ACTION_NEXT_AT_MOVEMENT_GRANULARITY, ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, ACTION_SET_SELECTION]
E/AccessibilityNodeInfoCache( 2837): Node from: 1139 not from:1145 android.view.accessibility.AccessibilityNodeInfo@233e7; boundsInParent: Rect(0, 342 - 192, 540); boundsInScreen: Rect(563, 1095 - 755, 1293); packageName: de.grobox.liberario; className: android.widget.Button; text: 30; contentDescription: null; viewIdResName: null; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: true; longClickable: true; enabled: true; password: false; scrollable: false; [ACTION_CLICK, ACTION_ACCESSIBILITY_FOCUS]
E/AccessibilityNodeInfoCache( 2837): Node from: 1139 not from:1145 android.view.accessibility.AccessibilityNodeInfo@23406; boundsInParent: Rect(0, 198 - 192, 342); boundsInScreen: Rect(563, 951 - 755, 1095); packageName: de.grobox.liberario; className: android.widget.EditText; text: 29; contentDescription: null; viewIdResName: android:id/numberpicker_input; checkable: false; checked: false; focusable: true; focused: false; selected: false; clickable: true; longClickable: true; enabled: true; password: false; scrollable: false; [ACTION_FOCUS, ACTION_SELECT, ACTION_CLEAR_SELECTION, ACTION_CLICK, ACTION_LONG_CLICK, ACTION_ACCESSIBILITY_FOCUS, ACTION_NEXT_AT_MOVEMENT_GRANULARITY, ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, ACTION_SET_SELECTION]
E/AccessibilityNodeInfoCache( 2837): Node from: 1139 not from:1145 android.view.accessibility.AccessibilityNodeInfo@23425; boundsInParent: Rect(0, 0 - 192, 198); boundsInScreen: Rect(563, 753 - 755, 951); packageName: de.grobox.liberario; className: android.widget.Button; text: 28; contentDescription: null; viewIdResName: null; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: true; longClickable: true; enabled: true; password: false; scrollable: false; [ACTION_CLICK, ACTION_ACCESSIBILITY_FOCUS]
E/AccessibilityNodeInfoCache( 2837): Node from: 1139 not from:1145 android.view.accessibility.AccessibilityNodeInfo@220e4; boundsInParent: Rect(0, 0 - 1026, 1028); boundsInScreen: Rect(27, 483 - 1053, 1511); packageName: de.grobox.liberario; className: android.widget.FrameLayout; text: null; contentDescription: null; viewIdResName: null; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; enabled: true; password: false; scrollable: false; [ACTION_SELECT, ACTION_CLEAR_SELECTION, ACTION_ACCESSIBILITY_FOCUS]
E/AccessibilityNodeInfoCache( 2837): Node from: 1139 not from:1145 android.view.accessibility.AccessibilityNodeInfo@22866; boundsInParent: Rect(0, 0 - 834, 88); boundsInScreen: Rect(123, 559 - 957, 647); packageName: de.grobox.liberario; className: android.widget.TextView; text: Uhrzeit festlegen; contentDescription: null; viewIdResName: android:id/alertTitle; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; enabled: true; password: false; scrollable: false; [ACTION_SELECT, ACTION_CLEAR_SELECTION, ACTION_ACCESSIBILITY_FOCUS, ACTION_NEXT_AT_MOVEMENT_GRANULARITY, ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, ACTION_SET_SELECTION]
E/AccessibilityNodeInfoCache( 2837): Node from: 1139 not from:1145 android.view.accessibility.AccessibilityNodeInfo@22c27; boundsInParent: Rect(0, 0 - 930, 636); boundsInScreen: Rect(75, 705 - 1005, 1341); packageName: de.grobox.liberario; className: android.widget.TimePicker; text: null; contentDescription: null; viewIdResName: android:id/timePicker; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; enabled: true; password: false; scrollable: false; [ACTION_SELECT, ACTION_CLEAR_SELECTION, ACTION_ACCESSIBILITY_FOCUS]
E/AccessibilityNodeInfoCache( 2837): Node from: 1139 not from:1145 android.view.accessibility.AccessibilityNodeInfo@22fe8; boundsInParent: Rect(0, 0 - 930, 144); boundsInScreen: Rect(75, 1343 - 1005, 1487); packageName: de.grobox.liberario; className: android.widget.Button; text: Fertig; contentDescription: null; viewIdResName: android:id/button1; checkable: false; checked: false; focusable: true; focused: false; selected: false; clickable: true; longClickable: false; enabled: true; password: false; scrollable: false; [ACTION_FOCUS, ACTION_SELECT, ACTION_CLEAR_SELECTION, ACTION_CLICK, ACTION_ACCESSIBILITY_FOCUS, ACTION_NEXT_AT_MOVEMENT_GRANULARITY, ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, ACTION_SET_SELECTION]
E/AccessibilityNodeInfoCache( 2837): Node from: 1139 not from:1145 android.view.accessibility.AccessibilityNodeInfo@233a9; boundsInParent: Rect(0, 0 - 192, 540); boundsInScreen: Rect(563, 753 - 755, 1293); packageName: de.grobox.liberario; className: android.widget.NumberPicker; text: null; contentDescription: null; viewIdResName: null; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; enabled: true; password: false; scrollable: true; [ACTION_ACCESSIBILITY_FOCUS, ACTION_SCROLL_FORWARD, ACTION_SCROLL_BACKWARD]
E/AccessibilityNodeInfoCache( 2837): Node from: 1139 not from:1145 android.view.accessibility.AccessibilityNodeInfo@23b2b; boundsInParent: Rect(524192, 0 - 524384, 73); boundsInScreen: Rect(325, 986 - 517, 1059); packageName: de.grobox.liberario; className: android.widget.EditText; text: 12; contentDescription: null; viewIdResName: android:id/numberpicker_input; checkable: false; checked: false; focusable: true; focused: false; selected: false; clickable: true; longClickable: true; enabled: true; password: false; scrollable: false; [ACTION_FOCUS, ACTION_SELECT, ACTION_CLEAR_SELECTION, ACTION_CLICK, ACTION_LONG_CLICK, ACTION_ACCESSIBILITY_FOCUS, ACTION_NEXT_AT_MOVEMENT_GRANULARITY, ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, ACTION_SET_SELECTION]
```

**Comment by grote** [comment]
Thanks for the log. Could you please also tell me how I can reproduce this crash? Where do I find an Accessibility Service and how do I run it?

**Comment by DJaeger** [comment]
The simplest to test is to install BrailleBack from Play Store.
You can activate it in accessible services (Bedienungshilfen) in system section in settings app.
Then start Liberario and press the dep/arr button, it doesn't change.
Or press the search button and the app will crash.

Alternatively you can activate Google TalkBack (should be preinstalled on gapps phones).
That one reads by default every item you hover and needs to doubletap any item to click.

Or you can use the appfill feature of the Lastpass app.

**Comment by grote** [comment]
Sorry, but all the apps you named are non-free apps and I am not using non-free software. That's the reason I wrote Liberario. Are there no Free Software accessibility services I could use to debug this?

**Comment by DJaeger** [comment]
I found none, that uses this info.
But you should be able to try with the old version of TalkBack that is available on F-Droid, as it seems to cause the same error.

**Comment by grote** [comment]
Thanks, TalkBack is great! Didn't crash on my phone, but could reproduce it with an earlier Android version in an emulator. Not fun debugging though. Please don't find more of those ;)

**Comment by DJaeger** [comment]
Works now with all tested accessebility services.
Thanks.
